server:
  servlet:
    session:
      timeout: 60m
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/words
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
