server:
  port: 8081
  servlet:
    session:
      timeout: 120m
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/words
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
training:
  amount: 30  # Будем выдавать в одну тренировку именно столько слов. Когда-нибудь можно будет это перенести в личные настройки
  factor:
    incorrect: 1.41 # Множитель для увеличения веса при ошибке
    correct: 0.8 # Множитель для уменьшения веса при правильном ответе
    renew: 1.05 # Множитель для повышения веса при отсутствии слов для тренировки
    threshold: 1.0  # Порог выборки переводов для тренировки. Будут выбираться переводы, у которых вес более этого числа.